### ISSUE TITLE
Compile error with latest code

### ISSUE THREAD

**Issue by mscherotter** [microsoftarchive/openFrameworks#57]
I am seeing a few problems with the WInRT build:

1>  ofAppWinRTWindow.cpp
1>c:\users\mischero\source\repos\openframeworks\libs\poco\include\poco\thread_win32.h(131): error C2668: 'TlsAlloc' : ambiguous call to overloaded function (C:\Users\mischero\Source\Repos\openFrameworks\libs\openFrameworks\app\ofAppWinRTWindow.cpp)
1>          c:\program files (x86)\windows kits\8.1\include\um\processthreadsapi.h(408): could be 'DWORD TlsAlloc(void)'
1>c:\users\mischero\source\repos\openframeworks\libs\poco\include\poco\thread_win32.h(193): error C2668: 'Sleep' : ambiguous call to overloaded function (C:\Users\mischero\Source\Repos\openFrameworks\libs\openFrameworks\app\ofAppWinRTWindow.cpp)
1>          c:\program files (x86)\windows kits\8.1\include\um\synchapi.h(908): could be 'void Sleep(DWORD)'
1>

**Comment by stammen** [comment]
What branch are you using?

**Comment by mscherotter** [comment]
universal

Sent from Windows Mail

From: Dale Stammen
Sent: ‎Friday‎, ‎November‎ ‎14‎, ‎2014 ‎3‎:‎39‎ ‎PM
To: MSOpenTech/openFrameworks
Cc: mscherotter

What branch are you using?

**Comment by stammen** [comment]
@anniruddh Would you please investigate?

**Comment by ghost** [comment]
Just came here to post the exact same bug.

I've been writing extensive getting started tutorials here (will port to my rbarraza.com site, so don't share too broadly yet, they're public but I'm not going to strongly advertise till they're all done):

Here is the illustrated step by step tutorial up until this error:
http://rbarraza.azurewebsites.net/2014/11/16/setup-openframeworks-rt-kinect-v2-for-windows-store/

(NOTE: I am testing and recommending the just release "Visual Studio Community 2013" as the free dev enviornment for both x64/VS2013 desktop dev and Windows Store dev moving forward with Kinect, so that's what I'm using for my IDE / compiler bits. The brand new one. It's pretty awesome.)

Like Michael, I'm getting the same error with TLSALLOC() in the Poco file now. I even tried an ugly hack of just prequalifying the offending file with a "using namespace ThreadEmulation" to see if that might at least get me compiling, but no go.

As reference, here are the other two tutorials all ready to go once I finish this third one and also write up how to wire up a Kinect V2 project with proper Solution paths and references.

Setting up OF X64 / VS2013 for Kinect V2:
http://rbarraza.azurewebsites.net/2014/11/15/setting-up-openframeworks-x64-kinect-v2-for-visual-studio-2013/

Setting up "official" OF with VS2012 for Kinect V2:
http://rbarraza.azurewebsites.net/2014/11/14/setting-up-openframeworks-kinect-v2-for-visual-studio-2012/

My blog post for Windows Store is Dead in the Water till this gets fixed.

Thanks Dale and A!

**Comment by mscherotter** [comment]
I am getting the compile error on the Universal branch.

Sent from Windows Mail

From: Rick Barraza
Sent: ‎Sunday‎, ‎November‎ ‎16‎, ‎2014 ‎10‎:‎43‎ ‎AM
To: MSOpenTech/openFrameworks
Cc: mscherotter

Unlike Michael, I am not using the WinRT build, but the more current Universal build.

Michael - you probably want to switch to Universal, it is more up to date and also gets you Phone.

This error is happening on Universal too ( in Visual Studio Community 2013 )

FYI

**Comment by stammen** [comment]
@anniruddh has just updated the universal branch with the fixes. He also added the latest version of ANGLE which should be about 30% faster framerate. Please let us know if you encounter any more issues.

**Comment by mscherotter** [comment]
That worked!

Sent from Windows Mail

From: Dale Stammen
Sent: ‎Monday‎, ‎November‎ ‎17‎, ‎2014 ‎8‎:‎37‎ ‎PM
To: MSOpenTech/openFrameworks
Cc: mscherotter

@ anniruddh has just updated the universal branch with the fixes. He also added the latest version of ANGLE which should be about 30% faster framerate. Please let us know if you encounter any more issues.
